//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int USR_ID { get; set; }
        public string USR_EMAIL { get; set; }
        public string USR_PASSWORD { get; set; }
        public string USR_FIRST_NAME { get; set; }
        public string USR_LAST_NAME { get; set; }
        public USR_GENDER USR_GENDER { get; set; }
        public bool USR_ACTIVE { get; set; }
        public Nullable<System.DateTime> USR_LAST_CONNECTION_DATETIME { get; set; }
        public System.DateTime USR_CREATION_DATETIME { get; set; }
        public System.DateTime USR_EDIT_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
